<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'App\Module'                                  => __DIR__ . '/Module.php',
    'App\Controller\BaseAbstractActionController' => __DIR__ . '/src/App/Controller/BaseAbstractActionController.php',
);
