<!DOCTYPE html>
<html>
<head>
    <title>M6分享厨房—<?php echo $this->result_array['recipe_name']?></title>
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/share/favicon.ico'))
        ->prependStylesheet($this->basePath() . '/css/share.css') ?>

</head>
<body>
<!--banner-->
<div id="banner">
    <div style="width: 320px; margin-left: auto; margin-right: auto; position: relative;">
        <a href="http://o2o.m6fresh.com/appdownload.aspx">
            <div style="position: absolute; left: 10px; top: 20px;"><img class="logo_img" src="/images/share/u2.png" width="75" height="75"/></div>
            <div style="position: absolute; left: 90px; top: 34px;"><span class="m6 font">M6</span></div>
            <div class="share font" style="position: absolute; left: 184px; top: 40px;">分享厨房</div>
            <div class="app font" style="position: absolute; left: 200px; top: 78px;">APP下载入口</div>
        </a>
    </div>
</div>

<div id="content font" style="margin-top: 10px;">
    <div class="cover" style="background-image:url(<?php echo $this->result_array['cover_image']?>)"></div>
    <div id="title" ><span><?php echo $this->result_array['recipe_name']?></span></div>
    <div id="author"><span>by <?php echo $this->result_array['author_name']?></span></div>
    <div id="intro" style="margin-top: 20px;"><p>简介</p><span> <?php echo str_replace("\n", "<br/>", $this->result_array['intro'])?></span></div>
    <div id="material" style="margin-top: 30px; margin-bottom: 30px;">
        <p>用料</p>
        <?php
        $m_count = count($this->materials);
        for($i = 0; $i < $m_count; $i++) {
            if ($i % 2 == 0) {
                echo '<span style="text-align: left;color:#383838;">'. $this->materials[$i] .'</span>';
            } else {
                echo '<span style="">'. $this->materials[$i] .'</span>';
                if ($i != $m_count - 1) {
                    echo '<div class="m_line"></div>';
                }

            }
        }
        ?>
    </div>

    <div id="steps" >
        <div style="margin-bottom: 20px;"><span style="font-size: 20px;font-weight: bold;">做法</span></div>
        <?php foreach($steps as $step) { ?>
            <div class="no">
                <span><?php echo $step['no']?></span>
            </div>
            <?php if ($step['img'] != '') { ?>
                <?php if (substr($step['img'],0,4) == 'http') {?>
                    <img class="step_img_img" src="<?php echo $step['img']?>"/>
                <?php } else {?>
                    <img class="step_img_img" src="<?php echo '/images/recipe/step/' . $step['img']?>"/>
                <?php }}?>
            <div class="step_content">
                <span><?php echo $step['content']?></span>
            </div>
        <?php }?>
    </div>

    <div id="tips">
        <span>小提示</span>
        <div class="step_content">
            <?php echo str_replace("\n", "<br/>", $this->result_array['tips'])?>
        </div>
    </div>
</div>
</body>
</html>
