<?php
    $form = $this->form;
    $form->prepare();
    /* @var $form User\Form\LoginForm */
    echo $this->form()->openTag($form);
    echo $this->formRow($form->get('login'));
    echo $this->formRow($form->get('password'));
    echo $this->formInput($form->get('submit'));
    echo $this->form()->closeTag($form);
?>
<?php 
    echo $this->errors;
?>
<div><a href="/user/register">Register</a></div>