<?php
    $form = $this->form;
    $form->prepare();
    echo $this->form()->openTag($form);
    echo $this->formRow($form->get('email'));
    echo $this->formRow($form->get('password'));
    echo $this->formRow($form->get('repassword'));
    echo $this->formRow($form->get('nickname'));
    echo $this->formInput($form->get('submit'));
    echo $this->form()->closeTag($form);
?>
<?php 
    echo $this->errors;
?>